#开发环境
server:
  # 服务器端口配置
  port: 80
  servlet:
    context-path:
spring:
  application:
    name: rqyzplatform
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://mysql.yl-mall.cn:3780/yl_rqhz?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=false&tinyInt1isBit=true
    username: root
    password: Mysql!2$
    druid:
      filters: stat
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 10
      min-idle: 10
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x' FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
  #设置开启热部署
  devtools:
    restart:
      enabled: true
  #页面不加载缓存，修改即时生效
  freemarker:
    cache: false
  # redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    timeout: 300
    jedis:
      pool:
        max-active: 8
        max-idle: 10
        min-idle: 5
        max-wait: 10000

  servlet:
    # 文件上传大小配置
    multipart:
      max-file-size: 2000MB
      max-request-size: 2000MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  mvc:
    static-path-pattern: /static/** #springboot首先匹配这个路径必须存在才允许访问资源，
    #如果不存在则直接404,不负责资源的位置。缺省是/**
    resources:
      static-locations: classpath:/static/  #前提是static-path-pattern必须匹配成功，
      #具体的资源在这个路径下去找
  #thymeleaf模本设置
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
    prefix: classpath:/templates/
    suffix: .html

mybatis-plus:
  typeAliasesPackage: com.yl.soft.po
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false
    db-config:
      id-type: auto

pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql
  auto-runtime-dialect: true
  default-count: true

# MinIO对象存储相关配置
minio:
  miniourl: http://119.3.222.171:9000 #M预览服务
  uploadurl: http://192.168.0.7:9000 #上传服务
  bucketName: mall #存储桶名称
  accessKey: minioadmin #访问的key
  secretKey: minioadmin #访问的秘钥
  expires: 60 #下载链有效期(s)

# 上传文件统一后缀名称配置
custom:
  flowNamelist: A001,A002,A003 #配置直播流名称
  yj:
    from: 1536466648@qq.com #发邮件人邮箱
    username: 1536466648 #发邮件人邮箱账号
    password: alhaihrpwsnubahb #授权密码
    host: smtp.qq.com #指定的smtp服务器
    protocol: smtp #设置发送邮件使用的协议
    ssl: 1 #是否开始ssl
    dk: 465 #端口
  hwyzb:
    live: rqyz.live.duoka361.com
    tlive: rqyz.tlive.duoka361.com
    appname: rqyz
    lkey: 3deYM0x8o8Fuq2ke
    tkey: mR9DFCwaOI0syBoz
  sms:
    time_out: 300
  yzm:
    url: https://139.9.32.119:18312/common/sms/sendTemplateMessage
    TemplateId0: SMS_20092900003 #注册
    TemplateId1: SMS_20092900003 #登录
    TemplateId2: SMS_20092900003 #绑定手机号
    TemplateId3: SMS_20092900003 #忘记密码
    TemplateId4: SMS_20092900003 #验证原手机号码
    TemplateId5: SMS_20092900003 #更换手机号码
    accout: ITA1039
    passward: DS6*%23du!a
  internal:
    key: Ji3452%8%#3lQ@kj%a*f91#69!A.o # 内部通讯Key
  session:
    time_out: 3600 # 超时秒
    cookie_name: _api_token
  authentication:
    pwd_salt: L0l*S0jn3SD*^OFY # 密码SALT
    enable_check_reqcode: true # 第三方登陆时是否用授权码获取openID，不开启则reqcode必须要传openID，保证唯一性
  wechat:
    app_id: wx9e91b1399c208e1e
    app_security: 200339db2289d67561d00db4d2777d75


  upload:
    ext:
      img: jpg,png,gif,ico,doc,docx,jpeg,apk,xls,xlsx,mp4,flv,swf,avi,mp3,pdf,txt,rar,zip,7z,tar
      audio: mp4,flv,swf,mkv,avi,rm,rmvb,mpeg,mpg,ogg,ogv,mov,wmv,webm,mp3,wav,mid
  #文件上传目录（注意Linux和Windows上的目录结构不同）
  uploadPath: D://uploadFiles/rqyz/
  image_upload_ext: jpg,png,gif,ico,doc,docx,jpeg,apk,xls,xlsx,mp4,flv,swf,avi,mp3,pdf,txt,rar,zip,7z,tar,mkv,avi,rm,rmvb,mpeg,mpg,ogg,ogv,mov,wmv,webm,wav,mid
  #外网可以访问上传图片ip地址
  ip: 127.0.0.1
  port: 80
  aes:
    key: s%1ldespACsl@ada #内部 aes 加密密钥
    parameter: 0aQ20$7V2(92&3*0 #";//内部 aes 加密偏移量
    value: 123dkds # 内部通信key

#腾讯云IM
tencent_yun:
  im:
    sdk_app_id: 1400433496
    secret_key: 5853ffdfd5c8c9f4f99fb4e26ae18a90fc84ce4eb17cdceea800ae7a528bd309
    expire_time: 100
    default_im_admin_account: administrator